spring.application.name=ai-news
spring.profiles.active=dev
spring.ai.google.genai.api-key=AQ.Ab8RN6LsZ1FVYC-oWP01N9FKOnuZsi9ikBt8GV5H-9tWhRUtmg
spring.ai.google.genai.chat.model=gemini-3.6-flash
logging.level.org.springframework.security=DEBUG